const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const sql=fs.readFileSync('supabase/migrations/202609160001_etapa1_tipo_fecha_efectiva.sql','utf8');
assert(html.includes('coi_confirmar_etapa_circuito_v3'),'frontend debe usar RPC v3');
assert(html.includes('p_fecha_efectiva'),'writer debe enviar fecha efectiva');
assert(html.includes('etapa1ModalFecha'),'modal debe ofrecer fecha efectiva editable');
assert(sql.includes('add column if not exists fecha_efectiva date'),'schema debe separar fecha efectiva');
assert(sql.includes("message='COI_STAGE_NOT_APPLICABLE_TO_TYPE'"),'servidor debe rechazar saldo remanente para Obra');
assert(sql.includes("message='COI_EFFECTIVE_DATE_FUTURE'"),'servidor debe rechazar fecha efectiva futura');
console.log('Etapa 1/2 fecha efectiva: controles base OK');
